export const connectorCategories = [
  "Marketing",
  "Messaging",
  "Productivity",
  "Sales",
  "Google",
  "Microsoft",
  "Developer",
  "AI & agents",
] as const

export type ConnectorCategory = (typeof connectorCategories)[number]
export type ConnectorFilter = "Enabled" | "All" | ConnectorCategory

export type ConnectorDefinition = {
  readonly id: string
  readonly name: string
  readonly description: string
  readonly categories: readonly ConnectorCategory[]
  readonly mark: string
  readonly color: string
  readonly enabled: boolean
}

export const connectorFilters: readonly ConnectorFilter[] = [
  "Enabled",
  "All",
  ...connectorCategories,
]

function connector(
  id: string,
  name: string,
  description: string,
  categories: readonly ConnectorCategory[],
  mark: string,
  color: string,
  enabled = false,
): ConnectorDefinition {
  return { id, name, description, categories, mark, color, enabled }
}

export const connectorCatalog: readonly ConnectorDefinition[] = [
  connector(
    "cloud",
    "Cloud",
    "Built-in backend, database, auth, and storage",
    ["Developer"],
    "CL",
    "#ff625f",
    true,
  ),
  connector(
    "openrouter",
    "OpenRouter",
    "Route prompts across the best frontier models",
    ["AI & agents", "Developer"],
    "OR",
    "#6f8cff",
    true,
  ),
  connector(
    "n8n",
    "n8n",
    "Run durable automations and agent workflows",
    ["Productivity", "Developer", "AI & agents"],
    "n8",
    "#ff6d5a",
    true,
  ),
  connector(
    "github",
    "GitHub",
    "Sync repositories, branches, issues, and deployments",
    ["Productivity", "Developer"],
    "GH",
    "#e9ebed",
    true,
  ),
  connector(
    "vercel",
    "Vercel",
    "Preview and publish every generated project",
    ["Developer", "Productivity"],
    "V",
    "#f8f8f5",
    true,
  ),
  connector(
    "openai",
    "OpenAI",
    "Build with reasoning, vision, voice, and embeddings",
    ["AI & agents"],
    "OA",
    "#65c9a4",
  ),
  connector(
    "anthropic",
    "Anthropic",
    "Use Claude models for agentic development",
    ["AI & agents"],
    "AI",
    "#d0a77b",
  ),
  connector(
    "google-ai",
    "Google Gemini",
    "Generate and analyze with Gemini models",
    ["AI & agents", "Google"],
    "GA",
    "#6f8cff",
  ),
  connector(
    "firecrawl",
    "Firecrawl",
    "AI-powered web scraping and retrieval",
    ["AI & agents", "Developer"],
    "FC",
    "#ff684f",
  ),
  connector(
    "perplexity",
    "Perplexity",
    "Ground agents with live web research",
    ["AI & agents", "Productivity"],
    "PX",
    "#41b6ad",
  ),
  connector(
    "stripe",
    "Stripe",
    "Accept payments and manage subscriptions",
    ["Sales", "Developer"],
    "S",
    "#766cff",
  ),
  connector(
    "resend",
    "Resend",
    "Send transactional and product email",
    ["Messaging", "Marketing", "Developer"],
    "R",
    "#e8e8e5",
  ),
  connector(
    "slack",
    "Slack",
    "Send messages and work with Slack workspaces",
    ["Messaging", "Productivity"],
    "SL",
    "#c774cd",
  ),
  connector(
    "telegram",
    "Telegram",
    "Automate conversations with Telegram bots",
    ["Messaging"],
    "TG",
    "#42a9df",
  ),
  connector(
    "discord",
    "Discord",
    "Build community bots and notifications",
    ["Messaging"],
    "DC",
    "#7289da",
  ),
  connector(
    "twilio",
    "Twilio",
    "Add SMS, voice, and messaging workflows",
    ["Messaging", "Marketing"],
    "TW",
    "#ef4f66",
  ),
  connector(
    "hubspot",
    "HubSpot",
    "Connect CRM, marketing, and customer data",
    ["Sales", "Marketing"],
    "HS",
    "#ff6948",
  ),
  connector(
    "salesforce",
    "Salesforce",
    "Connect accounts, leads, and opportunities",
    ["Sales"],
    "SF",
    "#48aee8",
  ),
  connector(
    "shopify",
    "Shopify",
    "Build and operate commerce experiences",
    ["Sales", "Marketing"],
    "SH",
    "#80b94b",
  ),
  connector(
    "linear",
    "Linear",
    "Create issues and manage product work",
    ["Productivity", "Developer"],
    "LN",
    "#b4b6c7",
  ),
  connector(
    "notion",
    "Notion",
    "Read and update pages and databases",
    ["Productivity"],
    "N",
    "#e8e8e5",
  ),
  connector(
    "airtable",
    "Airtable",
    "Connect structured data and automations",
    ["Productivity", "Marketing"],
    "AT",
    "#f3b74d",
  ),
  connector(
    "google-sheets",
    "Google Sheets",
    "Read and update spreadsheet data",
    ["Google", "Productivity"],
    "GS",
    "#45b981",
  ),
  connector(
    "google-drive",
    "Google Drive",
    "Upload, search, and download files",
    ["Google", "Productivity"],
    "GD",
    "#f4c84c",
  ),
  connector(
    "gmail",
    "Gmail",
    "Read, send, and manage email",
    ["Google", "Messaging"],
    "GM",
    "#ea625b",
  ),
  connector(
    "google-calendar",
    "Google Calendar",
    "Create events and coordinate schedules",
    ["Google", "Productivity"],
    "31",
    "#5891eb",
  ),
  connector(
    "google-search-console",
    "Google Search Console",
    "Inspect search performance and sites",
    ["Google", "Marketing"],
    "SC",
    "#e5b845",
  ),
  connector(
    "microsoft-outlook",
    "Microsoft Outlook",
    "Read, send, and manage email",
    ["Microsoft", "Messaging"],
    "OL",
    "#4d8ddd",
  ),
  connector(
    "microsoft-teams",
    "Microsoft Teams",
    "Send messages and manage channels",
    ["Microsoft", "Messaging"],
    "MT",
    "#7371d8",
  ),
  connector(
    "microsoft-excel",
    "Microsoft Excel",
    "Read and write spreadsheets",
    ["Microsoft", "Productivity"],
    "XL",
    "#45a36f",
  ),
  connector(
    "microsoft-onedrive",
    "Microsoft OneDrive",
    "Upload, find, and read files",
    ["Microsoft", "Productivity"],
    "OD",
    "#50a7dc",
  ),
]
